spring:
  profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/rms
    username: root
    password: ''
    class_driver: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
